### ISSUE TITLE
Plugin for IDE have incorrect suggestions if use controllers list bootstrap

### ISSUE THREAD

**Issue by BruLex** [L2jLiga/fastify-decorators-plugin#1]
I'm using IDE pligun, after upgrading fastify-decorators to 2.0.0-7 to use new feature *Bootstrap controllers by using controllers list*, I have removed all default export from my controllers and now IDE suggest to add it back, error **@ Controller must have default export**
Could you please fix this.

**Comment by L2jLiga** [comment]
Hi there,

Yeah, since 2.0.0-7 this inspection is out of date and I have to redo it.
Workaround is to disable inspection in IDE settings.

**Comment by L2jLiga** [comment]
Disabled it by default in 0.6.
Newer version will be published after moderation
